###Posting template data


http://localhost:4004/odata/v2/my/Templates

###Posting templates

POST http://localhost:4004/odata/v2/my/SaveTemplate
Content-Type: application/json

{
    "entries": [
        {
            "TemplateId": "template001",
            "TemplateDescription":"Template Description",
            "EmployeeExternalId": "EMP123",
            "Date": "2025-02-04",
            "WBSElement": "W01",
            "TaskType": "DEV",
            "TemplateId": "template002"
            "RecordedHours": 8.0
        },
        {
            "TemplateId": "template002",
            "TemplateDescription":"Template Description",
            "EmployeeExternalId": "EMP456",
            "Date": "2025-02-05",
            "WBSElement": "W02",
            "TaskType": "TST",
            "RecordedHours": 6.5
        }
    ]
}

###GET TemplateId
http://localhost:4004/odata/v2/my/GetAllTemplateIds

###
POST http://localhost:4004/odata/v2/my/GetTemplateData
Content-Type: application/json

{
    "TemplateId":"template001"
}